<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class AdminPermissionMenuTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        DB::table('admin_permission_menu')->delete();

        DB::table('admin_permission_menu')->insert([
            0 => [
                'permission_id' => 2,
                'menu_id'       => 32,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            1 => [
                'permission_id' => 2,
                'menu_id'       => 33,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            2 => [
                'permission_id' => 2,
                'menu_id'       => 34,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            3 => [
                'permission_id' => 2,
                'menu_id'       => 35,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            4 => [
                'permission_id' => 2,
                'menu_id'       => 36,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            5 => [
                'permission_id' => 2,
                'menu_id'       => 37,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            6 => [
                'permission_id' => 2,
                'menu_id'       => 38,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            7 => [
                'permission_id' => 2,
                'menu_id'       => 39,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            8 => [
                'permission_id' => 2,
                'menu_id'       => 40,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            9 => [
                'permission_id' => 2,
                'menu_id'       => 41,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            10 => [
                'permission_id' => 2,
                'menu_id'       => 42,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            11 => [
                'permission_id' => 2,
                'menu_id'       => 43,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            12 => [
                'permission_id' => 2,
                'menu_id'       => 44,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            13 => [
                'permission_id' => 2,
                'menu_id'       => 45,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            14 => [
                'permission_id' => 2,
                'menu_id'       => 46,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            15 => [
                'permission_id' => 2,
                'menu_id'       => 47,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            16 => [
                'permission_id' => 2,
                'menu_id'       => 48,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            17 => [
                'permission_id' => 2,
                'menu_id'       => 49,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            18 => [
                'permission_id' => 2,
                'menu_id'       => 50,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            19 => [
                'permission_id' => 2,
                'menu_id'       => 51,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            20 => [
                'permission_id' => 2,
                'menu_id'       => 52,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            21 => [
                'permission_id' => 3,
                'menu_id'       => 32,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            22 => [
                'permission_id' => 3,
                'menu_id'       => 33,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            23 => [
                'permission_id' => 3,
                'menu_id'       => 34,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            24 => [
                'permission_id' => 3,
                'menu_id'       => 35,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            25 => [
                'permission_id' => 3,
                'menu_id'       => 36,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            26 => [
                'permission_id' => 3,
                'menu_id'       => 37,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            27 => [
                'permission_id' => 3,
                'menu_id'       => 38,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            28 => [
                'permission_id' => 3,
                'menu_id'       => 39,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            29 => [
                'permission_id' => 3,
                'menu_id'       => 40,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            30 => [
                'permission_id' => 3,
                'menu_id'       => 41,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            31 => [
                'permission_id' => 3,
                'menu_id'       => 42,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            32 => [
                'permission_id' => 3,
                'menu_id'       => 43,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            33 => [
                'permission_id' => 3,
                'menu_id'       => 44,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            34 => [
                'permission_id' => 3,
                'menu_id'       => 45,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            35 => [
                'permission_id' => 3,
                'menu_id'       => 46,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            36 => [
                'permission_id' => 3,
                'menu_id'       => 47,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            37 => [
                'permission_id' => 3,
                'menu_id'       => 48,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            38 => [
                'permission_id' => 3,
                'menu_id'       => 49,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            39 => [
                'permission_id' => 3,
                'menu_id'       => 50,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            40 => [
                'permission_id' => 3,
                'menu_id'       => 51,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            41 => [
                'permission_id' => 3,
                'menu_id'       => 52,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            42 => [
                'permission_id' => 4,
                'menu_id'       => 32,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            43 => [
                'permission_id' => 4,
                'menu_id'       => 33,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            44 => [
                'permission_id' => 4,
                'menu_id'       => 34,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            45 => [
                'permission_id' => 4,
                'menu_id'       => 35,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            46 => [
                'permission_id' => 4,
                'menu_id'       => 36,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            47 => [
                'permission_id' => 4,
                'menu_id'       => 37,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            48 => [
                'permission_id' => 4,
                'menu_id'       => 38,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            49 => [
                'permission_id' => 4,
                'menu_id'       => 39,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            50 => [
                'permission_id' => 4,
                'menu_id'       => 40,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            51 => [
                'permission_id' => 4,
                'menu_id'       => 41,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            52 => [
                'permission_id' => 4,
                'menu_id'       => 42,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            53 => [
                'permission_id' => 4,
                'menu_id'       => 43,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            54 => [
                'permission_id' => 4,
                'menu_id'       => 44,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            55 => [
                'permission_id' => 4,
                'menu_id'       => 45,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            56 => [
                'permission_id' => 4,
                'menu_id'       => 46,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            57 => [
                'permission_id' => 4,
                'menu_id'       => 47,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            58 => [
                'permission_id' => 4,
                'menu_id'       => 48,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            59 => [
                'permission_id' => 4,
                'menu_id'       => 49,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            60 => [
                'permission_id' => 4,
                'menu_id'       => 50,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            61 => [
                'permission_id' => 4,
                'menu_id'       => 51,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            62 => [
                'permission_id' => 4,
                'menu_id'       => 52,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            63 => [
                'permission_id' => 5,
                'menu_id'       => 32,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            64 => [
                'permission_id' => 5,
                'menu_id'       => 33,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            65 => [
                'permission_id' => 5,
                'menu_id'       => 34,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            66 => [
                'permission_id' => 5,
                'menu_id'       => 35,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            67 => [
                'permission_id' => 5,
                'menu_id'       => 36,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            68 => [
                'permission_id' => 5,
                'menu_id'       => 37,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            69 => [
                'permission_id' => 5,
                'menu_id'       => 38,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            70 => [
                'permission_id' => 5,
                'menu_id'       => 39,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            71 => [
                'permission_id' => 5,
                'menu_id'       => 40,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            72 => [
                'permission_id' => 5,
                'menu_id'       => 41,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            73 => [
                'permission_id' => 5,
                'menu_id'       => 42,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            74 => [
                'permission_id' => 5,
                'menu_id'       => 43,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            75 => [
                'permission_id' => 5,
                'menu_id'       => 44,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            76 => [
                'permission_id' => 5,
                'menu_id'       => 45,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            77 => [
                'permission_id' => 5,
                'menu_id'       => 46,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            78 => [
                'permission_id' => 5,
                'menu_id'       => 47,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            79 => [
                'permission_id' => 5,
                'menu_id'       => 48,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            80 => [
                'permission_id' => 5,
                'menu_id'       => 49,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            81 => [
                'permission_id' => 5,
                'menu_id'       => 50,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            82 => [
                'permission_id' => 5,
                'menu_id'       => 51,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            83 => [
                'permission_id' => 5,
                'menu_id'       => 52,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            84 => [
                'permission_id' => 6,
                'menu_id'       => 32,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            85 => [
                'permission_id' => 6,
                'menu_id'       => 33,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            86 => [
                'permission_id' => 6,
                'menu_id'       => 34,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            87 => [
                'permission_id' => 6,
                'menu_id'       => 35,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            88 => [
                'permission_id' => 6,
                'menu_id'       => 36,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            89 => [
                'permission_id' => 6,
                'menu_id'       => 37,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            90 => [
                'permission_id' => 6,
                'menu_id'       => 38,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            91 => [
                'permission_id' => 6,
                'menu_id'       => 39,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            92 => [
                'permission_id' => 6,
                'menu_id'       => 40,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            93 => [
                'permission_id' => 6,
                'menu_id'       => 41,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            94 => [
                'permission_id' => 6,
                'menu_id'       => 42,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            95 => [
                'permission_id' => 6,
                'menu_id'       => 43,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            96 => [
                'permission_id' => 6,
                'menu_id'       => 44,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            97 => [
                'permission_id' => 6,
                'menu_id'       => 45,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            98 => [
                'permission_id' => 6,
                'menu_id'       => 46,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            99 => [
                'permission_id' => 6,
                'menu_id'       => 47,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            100 => [
                'permission_id' => 6,
                'menu_id'       => 48,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            101 => [
                'permission_id' => 6,
                'menu_id'       => 49,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            102 => [
                'permission_id' => 6,
                'menu_id'       => 50,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            103 => [
                'permission_id' => 6,
                'menu_id'       => 51,
                'created_at'    => null,
                'updated_at'    => null,
            ],
            104 => [
                'permission_id' => 6,
                'menu_id'       => 52,
                'created_at'    => null,
                'updated_at'    => null,
            ],
        ]);
    }
}
